/**
 * Dashboard Analytics Service
 * Computes KPIs, trends, distributions, and insights from simulation data
 */

import { formatCurrency } from '../../../engine/calculator.js';

/**
 * Get all dashboard KPIs
 * @param {Array} simulations
 * @param {Array} collaborators
 * @returns {Object} KPI metrics
 */
export function getDashboardKPIs(simulations, collaborators) {
  const totalSims = simulations.length;
  const totalCollabs = collaborators.length;
  const aiCount = simulations.filter(s => s.type === 'ai-analysis').length;

  let avgCost = 0;
  let totalSavings = 0;
  let avgTravelTime = 0;

  if (totalSims > 0) {
    const totalCost = simulations.reduce((s, sim) => s + (sim.resumo?.custoTotalEquipe || 0), 0);
    avgCost = totalCost / totalSims;
    avgTravelTime = simulations.reduce((s, sim) => s + (sim.resumo?.horasTransito || 0), 0) / totalSims;

    const comparisons = simulations.filter(s => s.type === 'comparison' || s.type === 'ai-analysis');
    if (comparisons.length >= 2) {
      const costs = comparisons.map(s => s.resumo?.custoTotalEquipe || 0).sort((a, b) => a - b);
      totalSavings = costs[costs.length - 1] - costs[0];
    }
  }

  return {
    totalSimulations: totalSims,
    totalCollaborators: totalCollabs,
    aiAnalysesCount: aiCount,
    averageCost: avgCost,
    totalSavings,
    averageTravelTime: avgTravelTime,
    simulationsToday: getSimulationsToday(simulations),
    comparisonCount: simulations.filter(s => s.type === 'comparison').length,
  };
}

/**
 * Get cost trend over time
 * @param {Array} simulations
 * @param {number} limit - Number of recent simulations
 * @returns {Array} Trend data points
 */
export function getCostTrend(simulations, limit = 15) {
  const recent = [...simulations].reverse().slice(0, limit);
  return recent.map((s, i) => ({
    index: i + 1,
    name: `#${i + 1}`,
    custo: s.resumo?.custoTotalEquipe || 0,
    transito: s.resumo?.horasTransito || 0,
    modal: s.modal || 'Outro',
    type: s.type || 'simulation',
    date: s.createdAt ? new Date(s.createdAt).toLocaleDateString('pt-BR') : '',
  }));
}

/**
 * Get travel mode distribution
 * @param {Array} simulations
 * @returns {Array} Distribution data
 */
export function getTravelModeDistribution(simulations) {
  const dist = {};
  simulations.forEach(s => {
    const modal = normalizeModal(s.modal);
    dist[modal] = (dist[modal] || 0) + 1;
  });
  return Object.entries(dist).map(([name, value]) => ({
    name,
    value,
    percentage: simulations.length > 0 ? Math.round((value / simulations.length) * 100) : 0,
  }));
}

/**
 * Get cost by destination (top expensive)
 * @param {Array} simulations
 * @param {number} limit
 * @returns {Array} Destinations by cost
 */
export function getCostByDestination(simulations, limit = 8) {
  const byDest = {};
  simulations.forEach(s => {
    const dest = s.destino || 'Outros';
    if (!byDest[dest]) byDest[dest] = { total: 0, count: 0 };
    byDest[dest].total += s.resumo?.custoTotalEquipe || 0;
    byDest[dest].count += 1;
  });

  return Object.entries(byDest)
    .map(([name, data]) => ({
      name: name.length > 20 ? name.substring(0, 18) + '...' : name,
      fullName: name,
      avgCost: Math.round(data.total / data.count),
      totalCost: Math.round(data.total),
      count: data.count,
    }))
    .sort((a, b) => b.avgCost - a.avgCost)
    .slice(0, limit);
}

/**
 * Get planned vs actual cost comparison
 * @param {Array} simulations
 * @returns {Array} Comparison data
 */
export function getPlannedVsActualCost(simulations) {
  // Group by route and compare simulations vs AI analyses
  const routes = {};
  simulations.forEach(s => {
    const route = `${s.origem || ''} → ${s.destino || ''}`;
    if (!routes[route]) routes[route] = { planned: [], actual: [] };
    if (s.type === 'ai-analysis') {
      routes[route].planned.push(s.resumo?.custoTotalEquipe || 0);
    } else {
      routes[route].actual.push(s.resumo?.custoTotalEquipe || 0);
    }
  });

  return Object.entries(routes)
    .filter(([_, data]) => data.planned.length > 0 || data.actual.length > 0)
    .map(([route, data]) => ({
      route,
      planned: data.planned.length > 0 ? Math.round(avg(data.planned)) : null,
      actual: data.actual.length > 0 ? Math.round(avg(data.actual)) : null,
      variance: data.planned.length > 0 && data.actual.length > 0
        ? Math.round(avg(data.actual) - avg(data.planned))
        : null,
    }))
    .slice(0, 10);
}

/**
 * Get savings generated by AI analyses
 * @param {Array} simulations
 * @returns {Object} Savings metrics
 */
export function getSavingsGeneratedByAI(simulations) {
  const aiSims = simulations.filter(s => s.type === 'ai-analysis');
  const manualSims = simulations.filter(s => s.type !== 'ai-analysis');

  const aiAvgCost = aiSims.length > 0
    ? aiSims.reduce((s, sim) => s + (sim.resumo?.custoTotalEquipe || 0), 0) / aiSims.length
    : 0;
  const manualAvgCost = manualSims.length > 0
    ? manualSims.reduce((s, sim) => s + (sim.resumo?.custoTotalEquipe || 0), 0) / manualSims.length
    : 0;

  return {
    aiAnalyses: aiSims.length,
    manualAnalyses: manualSims.length,
    aiAverageCost: Math.round(aiAvgCost),
    manualAverageCost: Math.round(manualAvgCost),
    estimatedSavings: Math.round(Math.max(0, manualAvgCost - aiAvgCost)),
    savingsPercentage: manualAvgCost > 0
      ? Math.round(((manualAvgCost - aiAvgCost) / manualAvgCost) * 100)
      : 0,
  };
}

/**
 * Get AI recommendation performance
 * @param {Array} simulations
 * @returns {Object} Performance metrics
 */
export function getRecommendationPerformance(simulations) {
  const aiSims = simulations.filter(s => s.type === 'ai-analysis');
  const byModal = {};

  aiSims.forEach(s => {
    const modal = normalizeModal(s.modal);
    if (!byModal[modal]) byModal[modal] = { count: 0, totalCost: 0, totalTime: 0 };
    byModal[modal].count += 1;
    byModal[modal].totalCost += s.resumo?.custoTotalEquipe || 0;
    byModal[modal].totalTime += s.resumo?.horasTransito || 0;
  });

  return Object.entries(byModal).map(([modal, data]) => ({
    modal,
    count: data.count,
    avgCost: Math.round(data.totalCost / data.count),
    avgTime: Math.round(data.totalTime / data.count * 10) / 10,
  }));
}

/**
 * Get team efficiency ranking
 * @param {Array} simulations
 * @param {Array} collaborators
 * @returns {Array} Efficiency metrics per collaborator
 */
export function getTeamEfficiencyRanking(simulations, collaborators) {
  // Simple metric: collaborators involved in most optimized scenarios
  return collaborators.map(c => ({
    name: c.nome,
    role: c.cargo,
    mobilizations: simulations.length, // All share same simulations in current model
    avgCostContribution: simulations.length > 0
      ? Math.round(simulations.reduce((s, sim) => s + (sim.resumo?.custoTotalEquipe || 0), 0) / simulations.length / collaborators.length)
      : 0,
  }));
}

/**
 * Get cost composition breakdown
 * @param {Array} simulations
 * @returns {Array} Cost categories
 */
export function getCostComposition(simulations) {
  if (simulations.length === 0) return [];

  const totals = { horas: 0, transito: 0, passagens: 0, hospedagem: 0, alimentacao: 0, logistico: 0 };
  simulations.forEach(s => {
    if (!s.resumo) return;
    totals.horas += s.resumo.custoEquipeHoras || 0;
    totals.transito += s.resumo.custoEquipeTransito || 0;
    totals.passagens += s.resumo.custoEquipePassagens || 0;
    totals.hospedagem += s.resumo.custoEquipeHospedagem || 0;
    totals.alimentacao += s.resumo.custoEquipeAlimentacao || 0;
    totals.logistico += s.resumo.custoLogistico || 0;
  });

  const grandTotal = Object.values(totals).reduce((a, b) => a + b, 0);

  return [
    { name: 'Mao de Obra', value: Math.round(totals.horas), percent: pct(totals.horas, grandTotal) },
    { name: 'Transito', value: Math.round(totals.transito), percent: pct(totals.transito, grandTotal) },
    { name: 'Passagens', value: Math.round(totals.passagens), percent: pct(totals.passagens, grandTotal) },
    { name: 'Hospedagem', value: Math.round(totals.hospedagem), percent: pct(totals.hospedagem, grandTotal) },
    { name: 'Alimentacao', value: Math.round(totals.alimentacao), percent: pct(totals.alimentacao, grandTotal) },
    { name: 'Logistico', value: Math.round(totals.logistico), percent: pct(totals.logistico, grandTotal) },
  ].filter(d => d.value > 0);
}

/**
 * Get recent route simulations
 * @param {Array} simulations
 * @param {number} limit
 * @returns {Array} Recent simulations
 */
export function getRecentRouteSimulations(simulations, limit = 5) {
  return simulations.slice(0, limit).map(s => ({
    id: s.id,
    name: s.nome || 'Simulacao',
    modal: s.modal || '-',
    origin: s.origem || '-',
    destination: s.destino || '-',
    teamSize: s.qtdColaboradores || 0,
    totalCost: s.resumo?.custoTotalEquipe || 0,
    transitTime: s.resumo?.horasTransito || 0,
    type: s.type || 'simulation',
    createdAt: s.createdAt,
  }));
}

/**
 * Generate AI insights from simulation data
 * @param {Array} simulations
 * @param {Array} collaborators
 * @returns {Array} Insight objects
 */
export function generateDashboardInsights(simulations, collaborators) {
  const insights = [];

  if (simulations.length === 0) {
    insights.push({ type: 'info', message: 'Crie simulacoes para receber insights automaticos de otimizacao.' });
    return insights;
  }

  // Mode that generated most savings
  const modeDistribution = getTravelModeDistribution(simulations);
  if (modeDistribution.length > 0) {
    const topMode = modeDistribution[0];
    insights.push({
      type: 'info',
      message: `${topMode.name} e o modal mais utilizado (${topMode.percentage}% das analises).`,
    });
  }

  // Most expensive destinations
  const topDests = getCostByDestination(simulations, 3);
  if (topDests.length > 0) {
    insights.push({
      type: 'warning',
      message: `Destino mais caro: ${topDests[0].fullName} com custo medio de ${formatCurrency(topDests[0].avgCost)}.`,
    });
  }

  // AI savings
  const savings = getSavingsGeneratedByAI(simulations);
  if (savings.estimatedSavings > 0) {
    insights.push({
      type: 'success',
      message: `Analises AI geram economia media de ${formatCurrency(savings.estimatedSavings)} por mobilizacao (${savings.savingsPercentage}%).`,
    });
  }

  // Average travel time warning
  const avgTime = simulations.reduce((s, sim) => s + (sim.resumo?.horasTransito || 0), 0) / simulations.length;
  if (avgTime > 10) {
    insights.push({
      type: 'warning',
      message: `Tempo medio de transito de ${avgTime.toFixed(1)}h — considere modais mais rapidos para reduzir horas improdutivas.`,
    });
  }

  // AI usage suggestion
  const aiPercentage = simulations.filter(s => s.type === 'ai-analysis').length / simulations.length;
  if (aiPercentage < 0.3) {
    insights.push({
      type: 'suggestion',
      message: 'Apenas ' + Math.round(aiPercentage * 100) + '% das analises usam AI. Aumente o uso da Inteligencia de Rotas para otimizar custos.',
    });
  }

  return insights;
}

// Helpers

function getSimulationsToday(simulations) {
  const today = new Date().toDateString();
  return simulations.filter(s => s.createdAt && new Date(s.createdAt).toDateString() === today).length;
}

function normalizeModal(modal) {
  if (!modal) return 'Outro';
  if (modal.includes('nibus') || modal.includes('Onibus')) return 'Onibus';
  if (modal.includes('reo') || modal.includes('Aereo')) return 'Aereo';
  if (modal.includes('culo') || modal.includes('Veiculo') || modal.includes('Frota')) return 'Veiculo';
  return modal;
}

function avg(arr) {
  return arr.length > 0 ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;
}

function pct(val, total) {
  return total > 0 ? Math.round((val / total) * 100) : 0;
}
